### ISSUE TITLE
Solicitation of Opinions for 1.14

### ISSUE THREAD

**Issue by realOxy** [realOxy/M3UAndroid#68]
> The development of a new version means that it may be a long time before the next official version is released.
## Missions
1. Theme selector.
2. Data backup and restore.
3. Supports for android tv.

**Comment by realOxy** [comment]
@realOxy

**Comment by realOxy** [comment]
Trying to generate scrim image dynamically, according to the screen size.
https://github.com/realOxy/M3UAndroid/blob/49cf65aa77c289c6f849b625d8dc62e7062a4e35/features/playlist/src/main/java/com/m3u/features/playlist/impl/TvPlaylistScreenImpl.kt#L227

**Comment by realOxy** [comment]
https://github.com/realOxy/M3UAndroid/assets/70512220/c53b1513-ac1d-4a97-bfaf-e7b4e7b15d48

**Comment by sguinetti** [comment]
Hello @realOxy  Thank you for notifying us of the new changes. Here my opinions.

1. I like how the interface is getting better and better. Now with the addition of Appearance section, I can see that you add several enhancements that we discussed earlier. By the way, when Appearance is accessed, a back button is needed.
2. The data backup plan is the same as the one I provided when I opened an issue. #60
3. About the TV interface. Since the TV is non-touch, the need to use physical buttons makes the experience very different. Should be necessary to find a way to use the contextual menu to make it easier, for example, to manage playlists.

**Comment by wuniversales** [comment]
Great, I have been testing on TV Box and the truth is that it has been a great job, it only has some bugs that I will comment below (I understand that it is an alpha version, but I comment everything I am seeing).

1- In the configuration menu, I would add an option to disable the animations (in order to improve the speed on slow devices).
2- The problem of the keyboard remains with the new interface, when it opens automatically and the focus stays in the first text field, you can't move to the second one. (Related to #67 )
3- When holding "OK" on the remote control (Being located above a list) I can visualize the edit menu, unsubscribe and copy url, but I can not scroll through any part of that menu.
(Related to #56 )
I commented a simple solution in the issue itself.
4- I can scroll through the player using the remote! Perfect
5- When scrolling channels to the right disappears the name of the category of the channel which can be confusing when you have many channels scrolled, I propose as a solution to place the name of the category in which the user is also at the top left, next to the name of the list put the category (Example: List 1 > Action).
6- The magnifying glass button to search for channels simply does not work for me.
7- "No image" mode in settings does not work.

This is all, Greetings

**Comment by realOxy** [comment]
@wuniversales 

The search button for tv has not been implemented yet.
The issue about auto requesting keyboard in textfields has not ways to solve temporary.

Some screens (foryou and favorite) menu dialog have not been replaced with tv style layouts yet, there is a menu (like, ban, save to gallery and create shortcut) which is tv layout is in playlist screen, trying it and let me know is it worked in your tv or not.

Have the animation and pictures cause your tv slow? Could you record a short video in your device?

My thought is hide zapping mode and no picture mode preferences in tv devices, but they are always on, auto preview channel in playlist screen background when staying in 3 seconds for it.

**Comment by realOxy** [comment]
@sguinetti To solve the text input, I consider to add a local network server for it. M3U app in your phone can scan the QR code in M3U app in your tv, then you can type text in your phone and it will be sent to tv side.

**Comment by realOxy** [comment]
If the local server worked, I think the https://github.com/realOxy/M3UAndroid/issues/70 may be replaced, users just search the m3u playlist result and share (https://github.com/realOxy/M3UAndroid/issues/66) them to the tv side.

Of course, they are also difficult to implement.

**Comment by realOxy** [comment]
alpha03: 
1. change channel title placement in tv playlist screen. @wuniversales 
2. fix some color mistakes
3. setting screen items now fit tv.

**Comment by wuniversales** [comment]
Good job with the categories, but now the player is not working, on the other hand, I have tried the menu you tell me (The menu to lock channels, create shortcut...) and I do not navigate through that menu, when I press the arrows of the controller, the focus remains in the background (I mean, I navigate through the channels, but I do not navigate through the submenu).
I'll see if I pass you a video by telegram.
Regards

**Comment by realOxy** [comment]
alpha04:
solved the tv playlist lag problem by bit operations. https://github.com/realOxy/M3UAndroid/commit/162598cf1db249c24ca7e31700475cb8fec84b27

**Comment by sguinetti** [comment]
> @sguinetti To solve the text input, I consider to add a local network server for it. M3U app in your phone can scan the QR code in M3U app in your tv, then you can type text in your phone and it will be sent to tv side.
> 
> If the local server worked, I think the #70 may be replaced, users just search the m3u playlist result and share (#66) them to the tv side.
> 
> Of course, they are also difficult to implement.

Interesting proposal, despite this is not what I was going to say. I apologize that I don't have an Android TV to test this feature. I still like that the feature help to link the media TV to the Android smartphone and being able to interact with the channels as if it were an additional remote control.

**Comment by sguinetti** [comment]
> alpha04:
> solved the tv playlist lag problem by bit operations. [162598c](https://github.com/realOxy/M3UAndroid/commit/162598cf1db249c24ca7e31700475cb8fec84b27)

@realOxy You labeled "latest" and not "prerelease" llike other alpha releases. Could you please correct it?

**Comment by realOxy** [comment]
@sguinetti oops, fixed

**Comment by realOxy** [comment]
alpha05,06:
tv playlist performance.
no picture mode for tv.
navigation for tv.

**Comment by realOxy** [comment]
![Screenshot_2024-01-22-01-43-01-699_com.m3u.androidApp.jpg](https://github.com/realOxy/M3UAndroid/assets/70512220/a3f66775-e6ef-4b9e-a47e-730ff9168a3f)

How can locate tv device in local network by at most 6 code?

What framework should I use to send messages between sever and client?

Considering the upgrade of communication rules, there may be downward incompatibility issues.

The framework must not unduly affect the final package size.

Options:
https://github.com/square/wire
https://eclipse.dev/jetty
https://zeromq.org

**Comment by realOxy** [comment]
NsdManager
ZeroMQ

**Comment by sguinetti** [comment]
A question, because I am learning about this topic, are all frameworks compatible with the Kotlin language or must be written in another programming language for them working?

**Comment by realOxy** [comment]
@sguinetti Kotlin is designed to be interoperable with Java, allowing seamless integration between Kotlin and Java code in Android projects. Kotlin can call Java code, and vice versa. Annotations, like @JvmName or @JvmStatic, can be used to enhance interoperability and make Kotlin code more compatible with Java, especially when dealing with specific language features.

**Comment by realOxy** [comment]
@sguinetti For android projects, we can use kotlin and java libraries directly, use native libraries by JNI.
