### ISSUE TITLE
Option to sort the list of favorites by most recent

### ISSUE THREAD

**Issue by sguinetti** [realOxy/M3UAndroid#83]
**Is your feature request related to a problem? Please describe.**
To take advantage of the potential of "recommend long-unseen favorite streams" and "Recently" shortcut, this feature helps to sort the list of favorites. Thus, you can alternatively review which channels you are watching recently and which ones you are not.

**Describe the solution you'd like**
In addition to the A-Z and Z-A sorting, a new "last viewed" sorting option has been added.

**Describe alternatives you've considered**
This feature takes advantage of which channels were last viewed. If it is implemented (https://github.com/realOxy/M3UAndroid/issues/42), possibly no other alternative is needed.

**Additional context**
This issue add one more option to know the behavior of the list. Perhaps users can access the channel they visit most frequently and so users can mark it as a favorite if they wish. As it is accessible from a menu, this function is not intrusive and does not affect the design of the app.

**Comment by realOxy** [comment]
It has now been implemented in the latest commit. It utilizes the same column "seen" (last viewed timestamp) as the "recommendation system," with its default value being the timestamp when the playlist was subscribed. Therefore, we won't see channels in the recommendation pager that are favorited but never played.

However, the conflict arises because if the column value is not specific (e.g., 0), all channels in recent sort mode will display a clear last played time instead of "never played." Additionally, I prefer not to add extra columns to distinguish whether a channel has been played.

The current behavior is the latter, where it shows the subscription playlist time even if it hasn't been played.

**Comment by sguinetti** [comment]
I think it could be solved by putting the streams that were not played yet at the end of the list without creating another column.  In this case, the priority order would be alphabetical and so the user would try one by one to position at the top of the sorting list.
